# Generated by Django 3.0.5 on 2020-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemonths',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
