# Generated by Django 3.0.5 on 2020-04-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0002_activemonths_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemonths',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='critters.Bug'),
        ),
        migrations.AlterField(
            model_name='activemonths',
            name='fish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='critters.Fish'),
        ),
    ]
