# Generated by Django 3.0.5 on 2020-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0003_auto_20200418_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='end_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='start_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='end_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='start_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
