# Generated by Django 3.0.5 on 2020-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0004_auto_20200418_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
