# Generated by Django 3.0.5 on 2020-04-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critters', '0006_auto_20200419_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='active_months',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='active_months',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activemonths',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_am', to='critters.Bug'),
        ),
        migrations.AlterField(
            model_name='activemonths',
            name='fish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_am', to='critters.Fish'),
        ),
    ]
